// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNg8_E3shlb-eX_DdYM6rmEYNA0oZIoKM',
    appId: '1:1076969686309:web:b963a0cd91a01770b8c6cc',
    messagingSenderId: '1076969686309',
    projectId: 'eng-egypt-2cccd',
    authDomain: 'eng-egypt-2cccd.firebaseapp.com',
    storageBucket: 'eng-egypt-2cccd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWc7pOR_hswmV5U8w7SRd63p7xiH8AJH4',
    appId: '1:1076969686309:android:30f78f5b2f1659b0b8c6cc',
    messagingSenderId: '1076969686309',
    projectId: 'eng-egypt-2cccd',
    storageBucket: 'eng-egypt-2cccd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW6Gkmk6pMxIDbfjBkxBOT0EAGXh8wm3Y',
    appId: '1:1076969686309:ios:fa1431133fe034d8b8c6cc',
    messagingSenderId: '1076969686309',
    projectId: 'eng-egypt-2cccd',
    storageBucket: 'eng-egypt-2cccd.appspot.com',
    androidClientId: '1076969686309-pl9oktiijfp9ab5k2brp5v9org74mc55.apps.googleusercontent.com',
    iosClientId: '1076969686309-gvm6mdpua7ej4l2uvapt8r03fb177tuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.engShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW6Gkmk6pMxIDbfjBkxBOT0EAGXh8wm3Y',
    appId: '1:1076969686309:ios:8b63637d1be099a9b8c6cc',
    messagingSenderId: '1076969686309',
    projectId: 'eng-egypt-2cccd',
    storageBucket: 'eng-egypt-2cccd.appspot.com',
    androidClientId: '1076969686309-pl9oktiijfp9ab5k2brp5v9org74mc55.apps.googleusercontent.com',
    iosClientId: '1076969686309-n82a2pqkrkbmd4lt6tq78eb80e2d9pb6.apps.googleusercontent.com',
    iosBundleId: 'com.example.engShop.RunnerTests',
  );
}
